## Python Libraries For Data Science

#### Data science is the process of deriving knowledge and insights from a huge and diverse set of data through organizing, processing and analysing the data.
#### There are nearly 20 python libraries for Data Science. Top five python libraries are
- TensorFlow 
- NumPy 
- SciPy 
- Pandas 
- Matplotlib
#### In those libraries, Numpy and Pandas are the first choice to the data scientists who are aware of the technologies.



## Introduction to NumPy

### The learning objectives of this section are:

- Understand advantages of vectorised code using NumPy (over standard python ways)
- Create NumPy arrays
- Convert lists and tuples to NumPy arrays
- Create (initialise) arrays
- Inspect the structure and content of arrays
- Subset, slice, index and iterate through arrays
- Compare computation times in NumPy and standard Python lists

## NumPy: (Numerical Python)

#### Numpy is Base N-Dimensional Array Package, is a python library and a fundamental 
#### package for scientific computing in Python. It is used to create multidimensional arrays
#### for fast operations. Use the following import conversion. 


## NumPy Arrays 
#### NumPy have a fixed size of arrays used to store a collection of elements, unlike 
#### python lists. There are three types of arrays called 1D, 2D and 3D arrays.


### Advantages of NumPy
#### We can write Vectorised code on numpy arrays, not on lists, which is convenient to read and write. 
#### Vectorized code typically does not contain explicit looping and indexing etc.
#### Numpy is much faster than the standard python ways to do computations


In [2]:
import numpy as ns

k=ns.array([2,5,9,7])

print(k)
print(type(k))

[2 5 9 7]
<class 'numpy.ndarray'>


In [3]:
# Multification of numbers using lists
list1=[1,5,6,7]
list2=[6,9,7,3]

h=list(map(lambda t1,t2:t1*t2,list1,list2))

h

[6, 45, 42, 21]

In [5]:
#multification of elements using numpy

n1=ns.array(list1)
n2=ns.array(list2)

n1*n2

array([ 6, 45, 42, 21])

In [6]:
# Declaration of two dimensional arrays
two_d=ns.array([[1,2,3],[4,5,6]])

two_d

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
two_d[1]

array([4, 5, 6])

In [9]:
two_d[1:]

array([[4, 5, 6]])

In [10]:
two_d[1,2]

6

In [11]:
two_d[::]

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
two_d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
two_d[:1]

array([[1, 2, 3]])

In [14]:
two_d[:,1]

array([2, 5])

In [15]:
# It prints array with given size with all elements in array as 1
ns.ones([10,10])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [16]:
ns.ones([5,5],dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
ns.zeros([10,15])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
ns.zeros([5,10],dtype="int")

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [19]:
ns.full([10,20],8)

array([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [20]:
ns.random.random(10)

array([0.57447331, 0.5994632 , 0.57700793, 0.01029904, 0.36525795,
       0.52476978, 0.9209183 , 0.93005717, 0.26805685, 0.9848804 ])

In [21]:
ns.random.randint(10,20,[10,10])

array([[17, 13, 12, 18, 19, 16, 17, 15, 16, 14],
       [19, 10, 18, 11, 14, 10, 13, 13, 14, 12],
       [16, 16, 19, 19, 19, 14, 18, 11, 18, 17],
       [17, 19, 12, 10, 12, 12, 10, 19, 14, 15],
       [17, 13, 13, 14, 15, 18, 18, 14, 18, 10],
       [18, 18, 19, 19, 13, 10, 10, 12, 17, 15],
       [18, 12, 12, 14, 17, 11, 19, 14, 11, 18],
       [19, 12, 19, 19, 14, 18, 13, 10, 19, 17],
       [10, 11, 11, 10, 11, 17, 16, 14, 11, 16],
       [12, 10, 14, 18, 11, 18, 11, 18, 19, 18]])

In [22]:
ns.eye(10,12)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]])

In [23]:
list1=[i for i in range(1,1000000)]
list2=[j**2 for j in range(1,1000000)]

import time

t1=time.time()
op=list(map(lambda x,y:x*y,list1,list2))
t2=time.time()

final_list=t2-t1

n1=ns.array(list1)
n2=ns.array(list2)

t3=time.time()
op1=n1*n2
t4=time.time()

final_num=t4-t3

print(final_list)
print(final_num)

0.31553220748901367
0.011658906936645508


In [25]:
ns.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [27]:
ns.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [30]:
g=ns.arange(1,25).reshape([4,3,2])

g

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [31]:
g[1,:,:]

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [34]:
print("shape:{}".format(ns.shape(g)))

shape:(4, 3, 2)


In [41]:
print("Data type: {}".format(ns.ndim(g)))

Data type: 3


In [44]:
a1=ns.arange(1,13).reshape(4,3)

a1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [46]:
a2=ns.arange(10,22).reshape(3,4)

a2

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [47]:
a1.dot(a2)

array([[ 92,  98, 104, 110],
       [218, 233, 248, 263],
       [344, 368, 392, 416],
       [470, 503, 536, 569]])

In [48]:
a1+a1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [49]:
a1*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [51]:
a3=ns.arange(1,17).reshape(4,4)

a3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [59]:
ns.linalg.inv(a3)

array([[ 1.50119988e+15, -3.75299969e+14, -3.75299969e+15,
         2.62709978e+15],
       [-1.95155984e+16,  1.95155984e+16,  1.95155984e+16,
        -1.95155984e+16],
       [ 3.45275971e+16, -3.79052969e+16, -2.77721977e+16,
         3.11498974e+16],
       [-1.65131986e+16,  1.87649984e+16,  1.20095990e+16,
        -1.42613988e+16]])

In [60]:
ns.linalg.det(a3)

-1.820448242817726e-31

In [61]:
a=ns.random.random(10)
a

array([0.98335841, 0.14465825, 0.97481619, 0.91842067, 0.47701818,
       0.66551175, 0.53891387, 0.76231068, 0.27583045, 0.9817094 ])

In [62]:
ns.sin(a)

array([0.83236339, 0.14415426, 0.82759873, 0.79464384, 0.45913227,
       0.61746176, 0.5132041 , 0.69059447, 0.27234609, 0.83144833])

In [63]:
ns.exp(a)

array([2.67341963, 1.15564456, 2.65067995, 2.50533051, 1.61126274,
       1.94548587, 1.71414407, 2.14322281, 1.31762444, 2.66901476])

In [64]:
ns.log(a)

array([-0.01678162, -1.93338121, -0.02550635, -0.08509975, -0.74020067,
       -0.40719898, -0.61819952, -0.27140108, -1.28796891, -0.01845994])

In [65]:
ns.tile([1,2,3],[2,3])

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3]])

In [71]:
ns.linalg.eig(a3)

(array([ 3.62093727e+01, -2.20937271e+00, -2.91421324e-15, -5.70557534e-16]),
 array([[-0.15115432,  0.72704996, -0.36400894,  0.00610215],
        [-0.34923733,  0.28320876,  0.79039305,  0.40008675],
        [-0.54732033, -0.16063243, -0.4887593 , -0.81847996],
        [-0.74540333, -0.60447363,  0.06237518,  0.41229105]]))